### ISSUE TITLE
无法调整字体

### ISSUE THREAD

**Issue by xue35** [CheYHinSpark/cvertbook#1]
你好，

很有意思的项目！我在学习你的项目的时候，发现更改```\documentclass[a5paper, 48pt, twocolumn]{cvertbook}```中字体大小和页面大小没有效果。

谢谢

**Comment by CheYHinSpark** [comment]
感谢关注，book文类提供的选项似乎只有10pt,11pt,12pt三种，可以试试用别的方式修改字体大小，不过48pt是不是太大了（

**Comment by xue35** [comment]
谢谢！虽然这个设置没法改变正文字体，不过还是用\Large实现了大字版。

另，我有兴趣加入你的中文直排24史项目。并且，建议做大字版。:-D

**Comment by CheYHinSpark** [comment]
我是排完史记了……二十四史太多了，我也不是文史专业的，遇到不同版本字词出入十分麻烦……感觉没有时间慢慢排了，主要我还把表也给排了，就导致工作量尤其大😂😂😂我已经放弃排完二十四史了
要是还排大字版……那得多少页啊😂😂😂

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月17日(周六) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CheYHinSpark/cvertbook] 无法调整字体 (#1)




 
谢谢！虽然这个设置没法改变正文字体，不过还是用\Large实现了大字版。
 
另，我有兴趣加入你的中文直排24史项目。并且，建议做大字版。:-D
